// includes/companies.js
module.exports = [
    { 'id': 1,  'project_id': 'shape-mhs-1',    'raw_dataset': 'servicetitan_shape_mhs_1'    },
    { 'id': 2,  'project_id': 'shape-chc-2',    'raw_dataset': 'servicetitan_shape_chc_2'    },
    { 'id': 3,  'project_id': 'shape-tucson-3', 'raw_dataset': 'servicetitan_shape_tucson_3' },
    { 'id': 4,  'project_id': 'shape-otm-4',    'raw_dataset': 'servicetitan_shape_otm_4'    },
    { 'id': 5,  'project_id': 'shape-aone-5',   'raw_dataset': 'servicetitan_shape_aone_5'   },
    { 'id': 6,  'project_id': 'shape-lba-6',    'raw_dataset': 'servicetitan_shape_lba_6'    },
    { 'id': 7,  'project_id': 'shape-lbca-7',   'raw_dataset': 'servicetitan_shape_lbca_7'   },
    { 'id': 8,  'project_id': 'shape-dear-8',   'raw_dataset': 'servicetitan_shape_dear_8'   },
    { 'id': 9,  'project_id': 'shape-hhwi-9',   'raw_dataset': 'servicetitan_shape_hhwi_9'   },
    { 'id': 10, 'project_id': 'shape-cls-10',   'raw_dataset': 'servicetitan_shape_cls_10'   },
    { 'id': 11, 'project_id': 'shape-hecs-11',  'raw_dataset': 'servicetitan_shape_hecs_11'  },
    { 'id': 12, 'project_id': 'shape-jsp-12',   'raw_dataset': 'servicetitan_shape_jsp_12'   },
    { 'id': 13, 'project_id': 'shape-ico-13',   'raw_dataset': 'servicetitan_shape_ico_13'   },
    { 'id': 14, 'project_id': 'shape-indy-14',  'raw_dataset': 'servicetitan_shape_indy_14'  },
    { 'id': 15, 'project_id': 'shape-lex-15',   'raw_dataset': 'servicetitan_shape_lex_15'   },
    { 'id': 16, 'project_id': 'shape-hze-16',   'raw_dataset': 'servicetitan_shape_hze_16'   },
    { 'id': 17, 'project_id': 'shape-ncva-17',  'raw_dataset': 'servicetitan_shape_ncva_17'  },
    { 'id': 18, 'project_id': 'shape-ahs-18',   'raw_dataset': 'servicetitan_shape_ahs_18'   },
    { 'id': 19, 'project_id': 'shape-ppp-19',   'raw_dataset': 'servicetitan_shape_ppp_19'   },
    { 'id': 20, 'project_id': 'shape-mgy-20',   'raw_dataset': 'servicetitan_shape_mgy_20'   },
    { 'id': 21, 'project_id': 'shape-ns-21',    'raw_dataset': 'servicetitan_shape_ns_21'    },
    { 'id': 22, 'project_id': 'shape-sst-22',   'raw_dataset': 'servicetitan_shape_sst_22'   },
    { 'id': 23, 'project_id': 'shape-jfsp-23',  'raw_dataset': 'servicetitan_shape_jfsp_23'  },
    { 'id': 24, 'project_id': 'shape-pthc-24',  'raw_dataset': 'servicetitan_shape_pthc_24'  },
    { 'id': 26, 'project_id': 'shape-cos-26',   'raw_dataset': 'servicetitan_shape_cos_26'   },
    { 'id': 27, 'project_id': 'shape-gem-27',   'raw_dataset': 'servicetitan_shape_gem_27'   },
    { 'id': 28, 'project_id': 'shape-newe-28',  'raw_dataset': 'servicetitan_shape_newe_28'  },
    { 'id': 29, 'project_id': 'shape-acga-29',  'raw_dataset': 'servicetitan_shape_acga_29'  },
    { 'id': 30, 'project_id': 'shape-jrb-30',   'raw_dataset': 'servicetitan_shape_jrb_30'   },
    { 'id': 31, 'project_id': 'shape-ida-31',   'raw_dataset': 'servicetitan_shape_ida_31'   }
];
