SELECT j.job_number                                                                         AS `Job Number`
     , TRIM(j.job_type_name)                                                                AS `Job Type`
     , TRIM(j.business_unit_name)                                                           AS `Business Unit`
     , j.project_number                                                                     AS `Project`
     , ROUND(j.total_invoice,2)                                                             AS `Job Total`
     , TRIM(j.technician_name)                                                              AS `Lead Generated By`
     , j.job_generated_lead_source_job_id                                                   AS `Lead Generated From`
     , ROUND(il.sub_total_lead,2)                                                           AS `Sales from Leads Created`
     , ROUND(j.total_invoice,2)                                                             AS `Subtotal`
     , DATE(`platform-partners-des.settings.fn_convert_utc_localtz`(j.completed_on,1))      AS `Completion Date`
     , j.customer_id                                                                        AS `Customer Id`
     , TRIM(j.customer_name)                                                                AS `Customer Name`
     , TRIM(j.technician_sold_name)                                                         AS `Sold By`
     , ARRAY_TO_STRING(IFNULL(j.assigned_technicians, []), ', ')                            AS `Assigned Technicians`
     , TRIM(j.primary_technician)                                                           AS `Primary Technician`
     , es.subtotal                                                                          AS `Estimate Sales Subtotal`
     , ei.estimate_items_total                                                              AS `Estimate Sales Installed`
     , ROUND(COALESCE(po.purchase_order_total,0),2)                                         AS `PO Costs`
     , TRIM(j.camapign_name)                                                                AS `Job Campaign`
     , TRIM(j.customer_type)                                                                AS `Cust Type`
     , j.summary                                                                            AS `Summary`
     , ARRAY_TO_STRING(IFNULL(jl.array_lead_created, []), ', ')                             AS `Lead Created`
     , ARRAY_TO_STRING(IFNULL(jl.array_lead_created_by, []), ', ')                          AS `Lead created By`
     , NULL                                                                                 AS `Payments`
     , ROUND(ts.total_paid_time,2)                                                          AS `Total Technicias Paid Time`
     , es.estimates                                                                         AS `Estimates`
     , ROUND(COALESCE(po.purchase_order_total,0) + COALESCE(ii.total_cost_mat_equ_invoice,0),2) AS `Material  Equip  PO Costs`
     , ROUND(-1*(COALESCE(re.returns_amount_total,0)),2)                                    AS `Returns`
  FROM `shape-mhs-1.dashboards.vw_pulse_base`                                               j      
  LEFT JOIN
        (
         WITH jobs_lead_created AS (
         SELECT job_generated_lead_source_job_id AS job_generated_lead_source_job_id
              , COUNT(id) AS cant_job
              , ARRAY_AGG(id IGNORE NULLS) AS array_job               
              , ARRAY_AGG(job_generated_lead_source_employee_id IGNORE NULLS) AS array_job2                             
           FROM `shape-mhs-1.servicetitan_shape_mhs_1.job` jobs_lead
          GROUP BY jobs_lead.job_generated_lead_source_job_id
         ),
         jobs_lead_created_by AS (
           SELECT jlc.job_generated_lead_source_job_id
                , lead_created_id AS job_id
                , jobs_individual.id AS job_id_verificado
                , jobs_individual.job_generated_lead_source_employee_id AS employee_id
                , tl.name AS technician_name
            FROM jobs_lead_created jlc
            LEFT JOIN UNNEST(jlc.array_job) AS lead_created_id
            LEFT JOIN `shape-mhs-1.servicetitan_shape_mhs_1.job` jobs_individual 
              ON jobs_individual.id = lead_created_id
            LEFT JOIN `shape-mhs-1.bronze.technician` tl 
              ON tl.id = jobs_individual.job_generated_lead_source_employee_id
         )
         SELECT job_generated_lead_source_job_id                                            AS job_generated_lead_source_job_id
              , ARRAY_AGG(CAST(job_id AS STRING) ORDER BY job_id)                           AS array_lead_created
              , ARRAY_AGG(TRIM(technician_name) ORDER BY job_id)                            AS array_lead_created_by
           FROM jobs_lead_created_by
          GROUP BY job_generated_lead_source_job_id
        )                                                                                   jl
   ON jl.job_generated_lead_source_job_id                                                   = j.id 

  LEFT JOIN 
       (
        SELECT invoice_lead.job_id                                                          AS job_id
             , SUM(invoice_lead.sub_total)                                                  AS sub_total_lead
          FROM `shape-mhs-1.servicetitan_shape_mhs_1.invoice`                               invoice_lead
         GROUP BY invoice_lead.job_id
       )                                                                                    il
    ON il.job_id                                                                            = j.job_generated_lead_source_job_id

  LEFT JOIN
       (
        SELECT job_id 
             , SUM(subtotal_cost_mat_equ_invoice)                                           AS total_cost_mat_equ_invoice
          FROM shape-mhs-1.servicetitan_shape_mhs_1.invoice                                 invoice
          LEFT JOIN
               (
                SELECT invoice_id
                     , SUM(cost*quantity)                                                   AS subtotal_cost_mat_equ_invoice
                  FROM shape-mhs-1.servicetitan_shape_mhs_1.invoice_item 
                  WHERE type IN ('Material','Equipment') 
                    AND active = TRUE 
                  GROUP BY invoice_id
               )                                                                            invoice_item
            ON invoice_item.invoice_id                                                      = invoice.id
         GROUP BY job_id            
       )                                                                                    ii            
     ON ii.job_id                                                                           = j.id

    
  LEFT JOIN `shape-mhs-1.servicetitan_shape_mhs_1.customer`                                 c
    ON c.id                                                                                 = j.customer_id
  LEFT JOIN 
       (
        SELECT job_id                                                                       AS job_id 
             , COUNT(estimate.id)                                                           AS estimates
             , SUM(subtotal)                                                                AS subtotal
          FROM `shape-mhs-1.servicetitan_shape_mhs_1.estimate`                              estimate
         WHERE sold_on                                                                      IS NOT NULL 
           AND active                                                                       IS TRUE
         GROUP BY                                                                           job_id
       )                                                                                    es 
    ON es.job_id                                                                            = j.id
  LEFT JOIN 
       (
        SELECT estimates.job_id                                                             AS estimates_job_id
             , SUM(estimate_items.total)                                                    AS estimate_items_total        
          FROM `shape-mhs-1.servicetitan_shape_mhs_1.estimate`                              estimates
          LEFT JOIN `shape-mhs-1.servicetitan_shape_mhs_1.estimate_item`                    estimate_items
            ON estimate_items.estimate_id                                                   = estimates.id
         WHERE estimates.active                                                             IS TRUE
           AND estimates.status_value                                                       = 1                
         GROUP BY                                                                           estimates.job_id
       )                                                                                    ei   
    ON ei.estimates_job_id                                                                  = j.id 
  LEFT JOIN 
       (
        SELECT jobs_timesheets.job_id
             , SUM(DATETIME_DIFF(jobs_timesheets.done_on, jobs_timesheets.dispatched_on, MINUTE)/60) AS total_paid_time
          FROM `shape-mhs-1.bronze.timesheet`                                               jobs_timesheets
         GROUP BY                                                                           jobs_timesheets.job_id
       )                                                                                    ts      
    ON ts.job_id                                                                            = j.id   
  LEFT JOIN 
       (
        SELECT job_id
             , SUM(total)                                                                   AS purchase_order_total
          FROM `shape-mhs-1.silver.vw_purchase_order`                                       purchase_orders
         GROUP BY                                                                           purchase_orders.job_id
       )                                                                                    po   
    ON po.job_id                                                                            = j.id
  LEFT JOIN 
       (
        SELECT job_id
             , SUM(return_amount)                                                           AS returns_amount_total
          FROM `shape-mhs-1.silver.vw_return`                                               returns
         GROUP BY                                                                           returns.job_id
       )                                                                                    re   
    ON re.job_id                                                                            = j.id

 WHERE j.job_status                                                                         = 'Completed'
   AND EXTRACT(YEAR FROM `platform-partners-des.settings.fn_convert_utc_localtz`(j.completed_on,1)) BETWEEN 2025 AND 2026
ORDER BY j.completed_on
;